sudo: false
before_install:
  - export PATH="/opt/ghc/7.8.4/bin:/opt/cabal/1.22/bin:$HOME/.cabal/bin:$PATH"
install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install alex happy
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
  - cabal build
after_script:
  - mkdir bundle
  - cp dist/build/pursuit/pursuit bundle/
  - cp LICENSE bundle/
  - tar czf pursuit.tar.gz -C bundle/ .
notifications:
  email: true
deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file: pursuit.tar.gz
  skip_cleanup: true
  on:
    tags: true
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.8.4
