resolver: lts-7.12
flags:
  pursuit:
    dev: true
packages:
- '.'
- location:
    git: https://github.com/paf31/barrier.git
    commit: 1d61f4db12e748e922c13c08c73889f78aced187
extra-deps:
- wai-middleware-gunzip-0.0.2
