resolver: lts-7.14
compiler: ghc-8.0.2
flags:
  pursuit:
    dev: true
packages:
- '.'
extra-deps:
- barrier-0.1.1
- purescript-0.10.6
- bower-json-1.0.0.1
- optparse-applicative-0.13.0.0
- turtle-1.3.1
