resolver: lts-7.12
flags:
  pursuit:
    dev: true
packages:
- '.'
- location:
    git: https://github.com/philopon/barrier.git
    commit: 22d9041bd01f4590f517ad7b426c665104eefd97
extra-deps:
- wai-middleware-gunzip-0.0.2
