resolver: lts-7.14
flags:
  pursuit:
    dev: true
packages:
- '.'
# Replace this once 0.10.5 is released
- location:
    git: https://github.com/purescript/purescript.git
    commit: f478e2f5ae5993f3cea42644a7e3ed252f662dd0
  extra-dep: true
extra-deps:
- barrier-0.1.1
- purescript-0.10.4
- bower-json-1.0.0.1
